name: Deploy

on:
  workflow_run:
    workflows: ["Generate Listing"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
            chmod +x .github/scripts/deploy.sh
            .github/scripts/deploy.sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_AKIENI_ACADEMY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
