name: Deploy

on:
  workflow_run:
    workflows: ["Listing"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_AKIENI_ACADEMY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=akieniacademy-eembouz-com
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
