name: Deploy

on:
  workflow_run:
    workflows: ["Generate Listing"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          npx wrangler pages project create akieniacademy-eembouz-com \
          --production-branch main || true
          npx wrangler pages deploy . --project-name=akieniacademy-eembouz-com
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_AKIENI_ACADEMY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
