name: Generate Listing

on:
  push:
    branches:
      - main

jobs:
  listing:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - run: npm install node-html-parser
      - run: node .github/scripts/getMeta.mjs

      - name: Detect changed TPs
        run: |
          git diff --name-only HEAD^1 HEAD^2 | grep -oE "^tp[^/]+" | sort -u > changed-tps.txt
          cat changed-tps.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-tps
          path: changed-tps.txt
          retention-days: 1

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add listing.json
          git diff --cached --quiet || git commit -m "update listing [skip ci]"
          git push origin main
