name: Deploy TPs

on:
  workflow_run:
    workflows: ["Generate Listing"]
    types: [completed]

permissions:
  actions: read

jobs:
  deploy-tps:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: changed-tps
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: |
          chmod +x .github/scripts/deploy-tp.sh

          if [ ! -s changed-tps.txt ]; then
            echo "skipping deploy"
            exit 0
          fi

          while read name; do
            [ -z "$name" ] && continue
            echo "→ Deploying $name"
            .github/scripts/deploy-tp.sh "$name"
          done < changed-tps.txt

        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_AKIENI_ACADEMY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
