name: Deploy TPs

on:
  workflow_run:
    workflows: ["Generate Listing"]
    types:
      - completed

jobs:
  deploy-tps:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy changed TPs
        run: |
          chmod +x .github/scripts/deploy-tp.sh
          SHA=${{ github.event.workflow_run.head_sha }}
          CHANGED=$(git diff --name-only $SHA~1 $SHA | grep -oE "^tp[^/]+" | sort -u)

          while read name; do
            .github/scripts/deploy-tp.sh "$name"
          done <<< "$CHANGED"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_AKIENI_ACADEMY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
